name: auto-badge

on:
  push:

    branches:
      - 'fix/*'
      - 'fixes/*'
      - 'feature/*'
      - 'features/*'
      - 'hotfix/*'
      - 'hotfixes/*'
      - 'release/*'
      - 'releases/*'
      - 'chore/*'
      - 'chores/*'

permissions: read-all

jobs:
  auto-badge:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO }}
        
    - name: Add License and Other Badges
      uses: rocktimsaikia/badge-it@master
      with:
        GITHUB_TOKEN: ${{ secrets.AUTO }}
        badges: 'gh_license, gh_version, gh_stars, gh_open_pr'
        badge-style: 'flat-square'
