name: workflow-badges

on:
  push:

    branches:
      - 'fix/*'
      - 'fixes/*'
      - 'feature/*'
      - 'features/*'
      - 'hotfix/*'
      - 'hotfixes/*'
      - 'release/*'
      - 'releases/*'
      - 'chore/*'
      - 'chores/*'

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  workflow-badges:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date '+%d-%m-%Y %H:%M:%S')"

    - name: Check for Workflow Badges in each folder with README
      shell: bash
      run: |
        parent_dir=$(pwd)
        directories=$(find . -not -path '*/.*' -type d -exec test -e '{}'/README.md \; -print)
        files=$(ls .github/workflows | grep "yaml")
        cmd="cat README.md | grep -i 'Build Status' | grep -o "
        for folder in ${directories} ; do
                echo "============================================"
                echo "*******| changing dir to ${folder} |******"
                cd ${parent_dir}
                cd "${folder}"
                for x in ${files}; do
                        echo running command: $cmd"${x}"
                        eval ${cmd}"${x}" > /dev/null 2>&1 || echo $? > /dev/null 2>&1
                        if [[ $_ == "${x}" ]]; then
                                echo "${x}" Badge Exists!!
                        else
                                echo "${x}" Badge NOT FOUND, Adding!
                                sed -i "1i \[!\[Build Status](https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions/workflows/"${x}"/badge.svg)](https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}/actions)   " README.md
                        fi
                done
        done

    - name: Push changes automatically!
      uses: EndBug/add-and-commit@v9
      with:
        message: '[Boldlinksig]: Missing workflow Badges added, files updated on ${{ steps.date.outputs.date }}.'
        author_name: boldlinksig
        author_email: boldlinksig@boldlink.io
        committer_name: boldlinksig
        committer_email: boldlinksig@boldlink.io
